version: "3.8"

name: dulich-app

services:
  db:
    image: mysql:latest
    container_name: dulichdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 161003
    volumes:
      - dulich-volume:/var/lib/mysql
    ports:
      - "3304:3306"
    networks:
      - dulich-network

  python-app:
    build: .
    depends_on:
      - db
    environment:
      MYSQL_HOST: dulichdb
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 161003
    ports:
      - "5000:5000"
    networks:
      - dulich-network

volumes:
  dulich-volume:

networks:
  dulich-network:
